### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by ElijahAlly** [ElijahAlly/BigTimeSound#2]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/ElijahAlly/BigTimeSound/wiki/mvp-list) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments

**Comment by iProgYou** [comment]
- Please mention which one is your CRUD feature. 
- Third MVP needs to be more fundamental. Song playback for example (with a song index page?)
