### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by ElijahAlly** [ElijahAlly/BigTimeSound#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased, and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name is lowercased, snake_cased, and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments

**Comment by iProgYou** [comment]
- What is the significance of the `album_id` in the artists table? Also, I think an artist needs a name. 
- How might an album have many songs if it can only reference one `song_id`?
- How can a playlist contain many songs if it only holds 1 song id and a user id? 

Happy to talk these through a bit
