### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ElijahAlly** [ElijahAlly/BigTimeSound#4]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically, any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments

**Comment by iProgYou** [comment]
- `songQueue` seems like it needs to be an array and not an object. I think you need a whole other songs slice of state
- I don't think you need a `playlist_id` within a playlist. Maybe the user who created the playlist's id? Also maybe song ids?

**Comment by iProgYou** [comment]
I think you will want to avoid doing a queue for now. that can be a later MVP
